package handlr

// Code generated by gohandlr. DO NOT EDIT.

import (
	"fmt"
	"github.com/epentland/gohandlr/pkg/gohandlr"
	"github.com/go-chi/chi/v5"
	"net/http"
	"strconv"
)

// PUT request to /users/{id}
func HandlePutUsersId(options ...gohandlr.Option) (string, string, http.HandlerFunc) {

	paramReader := gohandlr.WithParamsReader(func(r *http.Request, v interface{}) error {
		req, ok := v.(*PutUsersIdInput)
		if !ok {
			return fmt.Errorf("invalid type")
		}

		Id := chi.URLParam(r, ("id"))

		IdInt, err := strconv.Atoi(Id)
		if err != nil {
			return err
		}
		req.Id = IdInt

		return nil
	})
	options = append([]gohandlr.Option{paramReader}, options...)

	return "PUT", "/users/{id}", gohandlr.HandlerWithRequestWithResponse(processPutUsersId, options...)
}
