package handlr

// Code generated by gohandlr. DO NOT EDIT.

import (
	"context"
	"fmt"
	"github.com/epentland/gohandlr/pkg/gohandlr"
	"github.com/go-chi/chi/v5"
	"net/http"
	"strconv"
)

// HandleGetUsersId handles the GET request to /users/{id} with a request and response.
func HandleGetUsersId(process func(ctx context.Context, req GetUsersIdInput) (User, error), options ...gohandlr.Option) (string, string, http.HandlerFunc) {

	paramReader := gohandlr.WithParamsReader(func(r *http.Request, v interface{}) error {
		req, ok := v.(*GetUsersIdInput)
		if !ok {
			return fmt.Errorf("invalid type")
		}

		Id := chi.URLParam(r, ("id"))

		IdInt, err := strconv.Atoi(Id)
		if err != nil {
			return err
		}
		req.Id = IdInt

		Include := r.URL.Query().Get("include")

		req.Include = Include

		return nil
	})
	options = append([]gohandlr.Option{paramReader}, options...)

	return "GET", "/users/{id}", gohandlr.HandlerWithRequestWithResponse(process, options...)
}

// HandlePostUsersId handles the POST request to /users/{id} with a request no response.
func HandlePostUsersId(process func(ctx context.Context, req PostUsersIdInput) error, options ...gohandlr.Option) (string, string, http.HandlerFunc) {
	return "POST", "/users/{id}", gohandlr.HandlerWithRequestNoResponse(process, options...)
}
