// Code generated by gohandlr. DO NOT EDIT.
package handlr

type PutUsersIdInput struct {
	Id   int `json:"id" path:"id"`
	Body Company
}

type Address struct {
	City       string `json:"city"`
	PostalCode string `json:"postalCode"`
	Street     string `json:"street"`
}

type Company struct {
	Employees []User `json:"employees"`
	Name      string `json:"name"`
}

type User struct {
	Address Address `json:"address"`
	Email   string  `json:"email"`
	Id      int     `json:"id"`
	Name    string  `json:"name"`
}
